### ISSUE TITLE
The gender problem

### ISSUE THREAD

**Issue by VitalPS** [VitalPS/the_warpeds_game#1]
Given a gender, how to modify a word inside a statement to suit that gender in Python?

Example:
```
if gender == 'Masculine':
   print('You are a waiter.')
elif gender == 'Feminine':
   print('You are a waitress.')
```

Is there a simpler manner to achieve that?

**Comment by JBthePenguin** [comment]
Maybe this:
```python
words = {'Masculine': 'waiter', 'Feminine': 'waitress'}
print(f'You are a {words[gender]}.')
```

**Comment by VitalPS** [comment]
> Maybe this:
> 
> ```python
> words = {'Masculine': 'waiter', 'Feminine': 'waitress'}
> print(f'You are a {words[gender]}.')
> ```
That is a good idea! 

Unfortunately, my native language (Portuguese) has many conjugations and different words depending on the gender that you are dealing with. So, it seems that I will have to put all of these different words inside a dictionary, as you advised, and call them whenever they are necessary.

But that option is surely better than using "If, Elif" all the time! ^^

Thank you so much!
